<a href="https://colab.research.google.com/github/24pa1a45b1-source/24pa1a45b1-source.github.io/blob/main/House_predictionipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Housing.csv')
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
print(df.columns)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
df.groupby("price").mean()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
price,,,,,,,,,,,,,
1750000,3460.0,2.666667,1.0,1.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667
1767150,2400.0,3.000000,1.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000
1820000,3000.0,2.000000,1.0,1.000000,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.000000
1855000,2990.0,2.000000,1.0,1.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.000000
1890000,2674.5,2.500000,1.0,1.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10850000,7500.0,3.000000,3.0,1.000000,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.000000
11410000,7420.0,4.000000,1.0,2.000000,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.000000
12215000,7500.0,4.000000,2.0,2.000000,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.000000
12250000,9460.0,3.500000,3.0,3.000000,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.5,0.000000
13300000,7420.0,4.000000,2.0,3.000000,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.000000

In [ ]:
df.groupby("price")["area"].aggregate(["min","max"])

           min   max
price
1750000   2910  3850
1767150   2400  2400
1820000   3000  3000
1855000   2990  2990
1890000   1700  3649
...        ...   ...
10850000  7500  7500
11410000  7420  7420
12215000  7500  7500
12250000  8960  9960
13300000  7420  7420

[219 rows x 2 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
num_cols = ["price","area","stories","bedrooms","bathrooms","mainroad","guestroom"]
df[num_cols] = scaler.fit_transform(df[num_cols])
df[num_cols]

        price      area   stories  bedrooms  bathrooms  mainroad  guestroom
0    1.000000  0.396564  0.666667       0.6   0.333333       0.0        0.0
1    0.909091  0.502405  1.000000       0.6   1.000000       0.0        0.0
2    0.909091  0.571134  0.333333       0.4   0.333333       0.0        0.0
3    0.906061  0.402062  0.333333       0.6   0.333333       0.0        0.0
4    0.836364  0.396564  0.333333       0.6   0.000000       0.0        0.0
..        ...       ...       ...       ...        ...       ...        ...
540  0.006061  0.092784  0.000000       0.2   0.000000       0.0        0.0
541  0.001485  0.051546  0.000000       0.4   0.000000       0.0        0.0
542  0.000000  0.135395  0.000000       0.2   0.000000       0.0        0.0
543  0.000000  0.086598  0.000000       0.4   0.000000       0.0        0.0
544  0.000000  0.151203  0.333333       0.4   0.000000       0.0        0.0

[545 rows x 7 columns]

In [ ]:
Q1 = df["area"].quantile(0.25)
Q3 = df["area"].quantile(0.75)

IQR = Q3 - Q1

df = df[(df["area"] >= Q1 - 1.5*IQR) & (df["area"] <= Q3 + 1.5*IQR)]
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,1.000000,0.396564,0.6,0.333333,0.666667,0.0,0.0,0.0,0.0,0.0,2,0.0,False,False
1,0.909091,0.502405,0.6,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,3,0.0,False,False
2,0.909091,0.571134,0.4,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,2,0.0,True,False
3,0.906061,0.402062,0.6,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,3,0.0,False,False
4,0.836364,0.396564,0.6,0.000000,0.333333,0.0,0.0,0.0,0.0,0.0,2,0.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,0.006061,0.092784,0.2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,2,0.0,False,True
541,0.001485,0.051546,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,True,False
542,0.000000,0.135395,0.2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,False,True
543,0.000000,0.086598,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,False,False
544,0.000000,0.151203,0.4,0.000000,0.333333,0.0,0.0,0.0,0.0,0.0,0,0.0,False,True

In [ ]:
import numpy as np
df["area"] = np.log(df["area"])
df["price"] = np.log(df["price"])
df

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,-1.110223e-16,-0.924919,0.6,0.333333,0.666667,0.0,0.0,0.0,0.0,0.0,2,0.0,False,False
1,-9.531018e-02,-0.688348,0.6,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,3,0.0,False,False
2,-9.531018e-02,-0.560131,0.4,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,2,0.0,True,False
3,-9.864908e-02,-0.911149,0.6,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,3,0.0,False,False
4,-1.786918e-01,-0.924919,0.6,0.000000,0.333333,0.0,0.0,0.0,0.0,0.0,2,0.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,-5.105945e+00,-2.377486,0.2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,2,0.0,False,True
541,-6.512443e+00,-2.965273,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,True,False
542,-inf,-1.999557,0.2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,False,True
543,-inf,-2.446479,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,False,False
544,-inf,-1.889134,0.4,0.000000,0.333333,0.0,0.0,0.0,0.0,0.0,0,0.0,False,True

In [ ]:
corr = df.corr()

print(corr["price"].sort_values(ascending=False))
df

price                              1.000000
area                               0.542343
bathrooms                          0.423309
stories                            0.381196
bedrooms                           0.333312
parking                            0.318548
furnishingstatus_semi-furnished    0.143710
furnishingstatus_unfurnished      -0.347098
mainroad                                NaN
guestroom                               NaN
basement                                NaN
hotwaterheating                         NaN
airconditioning                         NaN
prefarea                                NaN
Name: price, dtype: float64

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,-1.110223e-16,-0.924919,0.6,0.333333,0.666667,0.0,0.0,0.0,0.0,0.0,2,0.0,False,False
1,-9.531018e-02,-0.688348,0.6,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,3,0.0,False,False
2,-9.531018e-02,-0.560131,0.4,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,2,0.0,True,False
3,-9.864908e-02,-0.911149,0.6,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,3,0.0,False,False
4,-1.786918e-01,-0.924919,0.6,0.000000,0.333333,0.0,0.0,0.0,0.0,0.0,2,0.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,-5.105945e+00,-2.377486,0.2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,2,0.0,False,True
541,-6.512443e+00,-2.965273,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,True,False
542,-inf,-1.999557,0.2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,False,True
543,-inf,-2.446479,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,False,False
544,-inf,-1.889134,0.4,0.000000,0.333333,0.0,0.0,0.0,0.0,0.0,0,0.0,False,True

In [ ]:
df["price_per_area"] = df["price"]/df["area"]
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished,price_per_area
0,-1.110223e-16,-0.924919,0.6,0.333333,0.666667,0.0,0.0,0.0,0.0,0.0,2,0.0,False,False,1.200346e-16
1,-9.531018e-02,-0.688348,0.6,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,3,0.0,False,False,1.384623e-01
2,-9.531018e-02,-0.560131,0.4,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,2,0.0,True,False,1.701568e-01
3,-9.864908e-02,-0.911149,0.6,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,3,0.0,False,False,1.082688e-01
4,-1.786918e-01,-0.924919,0.6,0.000000,0.333333,0.0,0.0,0.0,0.0,0.0,2,0.0,False,False,1.931972e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,-5.105945e+00,-2.377486,0.2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,2,0.0,False,True,2.147623e+00
541,-6.512443e+00,-2.965273,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,True,False,2.196237e+00
542,-inf,-1.999557,0.2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,False,True,inf
543,-inf,-2.446479,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0,0.0,False,False,inf
544,-inf,-1.889134,0.4,0.000000,0.333333,0.0,0.0,0.0,0.0,0.0,0,0.0,False,True,inf